name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ccr.ccs.tencentyun.com # optional
        # Username used to log against the Docker registry
        username: 100020142421 # optional
        # Password or personal access token used to log against the Docker registry
        password: Chen@1016 # optional
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true
    - name: Build the Docker image
      env:
        tag: 11
      run: |
        echo "tag=ccr.ccs.tencentyun.com/java_docker/code-server:$(date +%s)" >> $GITHUB_ENV
        echo '$tag' && docker build . --file Dockerfile --tag tag

    - name: push the Docker image
      run: echo "${{ env.tag }} ${{ env.tag1 }}" &&  docker push  ${{ env.tag }}


